version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: library
      POSTGRES_PASSWORD: library
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U library"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: library
      DB_USER: library
      DB_PASSWORD: library
      PORT: 8080
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    environment:
      - VITE_API_BASE_URL=http://localhost:8080
    command: sh -c "npm ci || npm i && npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173"
    depends_on:
      - app

volumes:
  dbdata:
