spring:
  application:
    name: 221b-library
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:library}
    username: ${DB_USER:library}
    password: ${DB_PASSWORD:library}
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: ${PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:postgresql://localhost:5432/library_test
    username: library
    password: library
  flyway:
    enabled: false
